routes/admin.php
<?php
Artisan::call('storage:link');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('backend.')->namespace('Backend')->group(function() {
    Route::get('/', 'BackendController@index')->name('home');
    Route::resource('feedback', 'FeedbackController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('frontend.')->namespace('Frontend')->group(function() {

    Route::get('/', 'FrontendController@index')->name('home');
    Route::post('/feedback/reply', 'FeedbackController@create_reply')->name('feedback.create_reply');
    Route::resource('feedback', 'FeedbackController');


});

app/Models/Feedback.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Feedback extends Model
{
    protected $table = 'feedback';

    protected $fillable = ['name', 'subject', 'message'];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    public function reply() {
        return $this->hasMany(Reply::class, 'feedback_id', 'id');
    }

}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendController extends Controller
{

    public function __construct()
    {

    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        return view('backend.index');
    }

}

app/Http/Controllers/Backend/FeedbackController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\ReplyRequest;
use App\Repositories\FeedbackRepository;
use App\Repositories\ReplyRepository;
use Illuminate\Http\Request;

class FeedbackController extends Controller
{

    public function __construct(FeedbackRepository $feedbackRepository, ReplyRepository $replyRepository)
    {
        $this->feedbackRepository = $feedbackRepository;
        $this->replyRepository = $replyRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $listFeedback = $this->feedbackRepository->paginated();
        return view('backend.feedback.index', compact('listFeedback'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.feedback.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ReplyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ReplyRequest $request)
    {
        $this->replyRepository->create($request->input());

        return redirect()->back()->with('flash_message', __('Reply Success'));
    }

    /**
     * Show the form for preview the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $feedback = $this->feedbackRepository->firstBy(['id' => $id]);
        if(!$feedback) return redirect()->route('backend.feedback.index');

        return view('backend.feedback.show', compact('feedback'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $feedback = $this->replyRepository->firstBy(['id' => $id]);
        if(!$feedback) return redirect()->route('backend.feedback.index');

        return view('backend.feedback.edit', compact('feedback'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\ReplyRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ReplyRequest $request, $id)
    {
        $data = $request->input();
        $this->replyRepository->update($id, $data);

        return redirect()->route('backend.feedback.index')->with('flash_message', __('Update Success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($this->feedbackRepository->customDestroy($id)) {
            return redirect()->back()->with('flash_message', __('Delete Success'));
        }
        return redirect()->back();
    }

}

app/Http/Controllers/Frontend/FeedbackController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\FeedbackRequest;
use App\Http\Requests\ReplyRequest;
use Illuminate\Http\Request;
use App\Repositories\FeedbackRepository;
use App\Repositories\ReplyRepository;

class FeedbackController extends Controller
{

    public function __construct(FeedbackRepository $feedbackRepository, ReplyRepository $replyRepository)
    {
        $this->feedbackRepository = $feedbackRepository;
        $this->replyRepository = $replyRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $listFeedback = $this->feedbackRepository->paginated();
        return view('frontend.feedback.index', compact('listFeedback'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('frontend.feedback.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\FeedbackRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(FeedbackRequest $request)
    {
        $this->feedbackRepository->create($request->input());

        return redirect()->route('frontend.feedback.index')->with('flash_message', __('Create Success'));
    }

    /**
     * Store a newly created reply resource in storage.
     *
     * @param  \Illuminate\Http\ReplyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function create_reply(ReplyRequest $request)
    {
        $this->replyRepository->create($request->input());

        return redirect()->back()->with('flash_message', __('Feedback Success'));
    }

    /**
     * Show the form for preview the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, Request $request)
    {
        $feedback = $this->feedbackRepository->firstBy(['id' => $id]);
        if(!$feedback) return redirect()->route('frontend.feedback.index');

        return view('frontend.feedback.show', compact('feedback'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $feedback = $this->feedbackRepository->firstBy(['id' => $id]);
        if(!$feedback) return redirect()->route('frontend.feedback.index');

        return view('frontend.feedback.edit', compact('feedback'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\FeedbackRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(FeedbackRequest $request, $id)
    {
        $data = $request->input();
        $this->feedbackRepository->update($id, $data);

        return redirect()->route('frontend.feedback.index')->with('flash_message', __('Update Success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($this->feedbackRepository->customDestroy($id)) {
            return redirect()->back()->with('flash_message', __('Delete Success'));
        }
        return redirect()->back();
    }

}

resources/views/backend/feedback/_form.blade.php
<div class="form-group">
    <label for="title" class="col-md-12 control-label"><span class="text-red">※</span>Name</label>
    <div class="col-md-12 @if($errors->has('subject')) has-error @endif">
        <input class="form-control" type="text" name="name" value="{{ old('name', $item->name) }}">
        <input name="id" type="hidden" value="{{ $item->id }}">
    </div>
    @if($errors->has('name'))
        <p class="text-danger">{{$errors->first('name')}}</p>
    @endif
</div>

<div class="form-group">
    <label for="title" class="col-md-12 control-label"><span class="text-red">※</span>Subject</label>
    <div class="col-md-12 @if($errors->has('subject')) has-error @endif">
        <input class="form-control" name="subject" type="text" value="{{ old('subject', $item->subject) }}">
    </div>
    @if($errors->has('subject'))
        <p class="text-danger">{{$errors->first('subject')}}</p>
    @endif
</div>

<div class="form-group">
    <label class="col-md-12 control-label">Message</label>
    <div class="col-md-12">
        <textarea class="form-control" name="message" rows="4">{{ old('message', nl2br($item->message)) }}</textarea>
    </div>
</div>

<p></p>

<div class="form-group">
    <div class="col-md-12 text-center">
        <a href="{{ route('backend.feedback.index') }}" title="Back">
            <button class="btn btn-default" type="button">Back</button>
        </a>
        <button class="btn btn-primary" type="submit">@if($item->id) Update @else Add @endif</button>
    </div>
</div>

resources/views/backend/feedback/create.blade.php
@extends('backend.layouts.master')

@section('title')
    Create
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
<p></p>
                <div class="card">
                    <div class="card-body">
                        <form class="form-horizontal js-form-validate" action="{{ route('backend.feedback.store') }}" method="POST">
                            @csrf
                            @include('backend.feedback._form', ['item' => optional(null) ])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/feedback/edit.blade.php
@extends('backend.layouts.master')

@section('title')
    Edit
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
<p></p>
                <div class="card">

                    <div class="card-body">
                        <form class="form-horizontal js-form-validate" action="{{ route('backend.feedback.update', $feedback->id) }}" method="POST">
                            @csrf
                            @method('PUT')
                            @include('backend.feedback._form', ['item' => $feedback])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/feedback/index.blade.php
@extends('backend.layouts.master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p></p>
                @if(session('flash_message'))
                    <div class="alert alert-success" role="alert">
                        {{session('flash_message')}}
                    </div>
                @endif
                <div class="card">

                    <div class="card-body">

                        <div class="table-responsive mt15">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th class="text-center">ID</th>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">Subject</th>
                                    <th class="text-center">View</th>
                                    <th class="text-center">Delete</th>
                                </tr>
                                </thead>
                                <tbody>
                                @if($listFeedback->total() > 0)
                                    @foreach($listFeedback as $item)
                                        <tr>
                                            <td class="text-center">{{ $item->id }}</td>
                                            <td class="text-center">{{ $item->name }}</td>
                                            <td class="text-center">{{ $item->subject }}</td>
                                            <td class="text-center">
                                                <a class="btn btn-sm btn-warning" href="{{ route('backend.feedback.show', $item->id) }}">View</a>
                                            </td>
                                            <td class="text-center">
                                                <form method="POST" class="form-delete"
                                                      action="{{ route('backend.feedback.destroy', $item->id) }}"
                                                      accept-charset="UTF-8" style="display:inline">
                                                    {{csrf_field()}}
                                                    {{ method_field('DELETE') }}
                                                    <button type="submit" class="btn btn-sm btn-danger js-delete-btn">
                                                        Delete
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td colspan="7">No data</td>
                                    </tr>
                                @endif
                                </tbody>
                            </table>
                        </div>
                        @if($listFeedback->total() > 0)
                            @include('common.paginator', ['paginator' => $listFeedback])
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/backend/feedback/show.blade.php
@extends('backend.layouts.master')

@section('title')
    Show
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">

<p></p>
                @if(session('flash_message'))
                    <div class="alert alert-success" role="alert">
                        {{session('flash_message')}}
                    </div>
                @endif
                <div class="card">

                    <div class="card-body">
                        <form class="form-horizontal js-form-validate" action="{{ route('backend.feedback.store') }}" method="POST">
                            @csrf
                            <div class="form-group">
                                <label for="title" class="col-md-6 control-label">Name : {{$feedback->name}}</label>
                                <input name="feedback_id" type="hidden" value="{{ $feedback->id }}">
                                <input name="type" type="hidden" value="1">
                            </div>
                            <div class="form-group">
                                <label for="title" class="col-md-12 control-label">Subject: {{$feedback->subject}}</label>
                            </div>
                            <div class="form-group">
                                <label for="title" class="col-md-12 control-label">Message: {!! nl2br($feedback->message) !!}</label>
                            </div>
                            @if(count($feedback->reply()->get()->toArray()) > 0)
                                <hr />
                                @foreach($feedback->reply()->get() as $value)
                                    <small>@if($value->type == 1) Reply @else Feedback @endif</small>
                                    <div class="card">
                                        <div class="card-body">
                                            <small>{{$value->created_at}}</small>
                                            <h5 class="card-title">{{$value->name}}</h5>
                                            <p class="card-text">{!! nl2br($value->message) !!}</p>
                                        </div>
                                    </div>
                                    <p></p>
                                @endforeach
                            @endif

                            <hr>

                            <div class="form-group">
                                <label for="title" class="col-md-12 control-label"><span class="text-red">※</span>Name</label>
                                <div class="col-md-12 @if($errors->has('name')) has-error @endif">
                                    <input class="form-control" type="text" name="name" value="{{ old('name', 'Admin') }}">
                                </div>
                                @if($errors->has('name'))
                                    <p class="text-danger">{{$errors->first('name')}}</p>
                                @endif
                            </div>

                            <div class="form-group">
                                <label class="col-md-12 control-label">Message</label>
                                <div class="col-md-12">
                                    <textarea class="form-control" name="message" rows="4">{{ old('message') }}</textarea>
                                </div>
                            </div>

                            <p></p>

                            <div class="form-group">
                                <div class="col-md-12 text-center">
                                    <a href="{{ route('backend.feedback.index') }}" title="Back">
                                        <button class="btn btn-default" type="button">Back</button>
                                    </a>
                                    <button class="btn btn-primary" type="submit">Reply</button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection