routes/admin.php
<?php
Artisan::call('storage:link');
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::prefix('admin')->name('backend.')->namespace('Backend')->group(function() {
    Route::get('/', 'BackendController@index')->name('home');
    Route::resource('feedback', 'FeedbackController');
});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::name('frontend.')->namespace('Frontend')->group(function() {

    Route::get('/', 'FrontendController@index')->name('home');
    Route::post('/feedback/reply', 'FeedbackController@create_reply')->name('feedback.create_reply');
    Route::resource('feedback', 'FeedbackController');


});

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class BackendController extends Controller
{

    public function __construct()
    {

    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        return view('backend.index');
    }

}

app/Http/Controllers/Backend/FeedbackController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\ReplyRequest;
use App\Repositories\FeedbackRepository;
use App\Repositories\ReplyRepository;
use Illuminate\Http\Request;

class FeedbackController extends Controller
{

    public function __construct(FeedbackRepository $feedbackRepository, ReplyRepository $replyRepository)
    {
        $this->feedbackRepository = $feedbackRepository;
        $this->replyRepository = $replyRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $listFeedback = $this->feedbackRepository->paginated();
        return view('backend.feedback.index', compact('listFeedback'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.feedback.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\ReplyRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ReplyRequest $request)
    {
        $this->replyRepository->create($request->input());

        return redirect()->back()->with('flash_message', __('Reply Success'));
    }

    /**
     * Show the form for preview the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $feedback = $this->feedbackRepository->firstBy(['id' => $id]);
        if(!$feedback) return redirect()->route('backend.feedback.index');

        return view('backend.feedback.show', compact('feedback'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $feedback = $this->replyRepository->firstBy(['id' => $id]);
        if(!$feedback) return redirect()->route('backend.feedback.index');

        return view('backend.feedback.edit', compact('feedback'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\ReplyRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ReplyRequest $request, $id)
    {
        $data = $request->input();
        $this->replyRepository->update($id, $data);

        return redirect()->route('backend.feedback.index')->with('flash_message', __('Update Success'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if ($this->feedbackRepository->customDestroy($id)) {
            return redirect()->back()->with('flash_message', __('Delete Success'));
        }
        return redirect()->back();
    }

}

resources/views/backend/common/footer.blade.php
<div class="container">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="{{route('backend.home')}}" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="{{route('backend.feedback.index')}}" class="nav-link px-2 text-muted">Feedback</a></li>
        </ul>
        <p class="text-center text-muted">© 2022 Company, Inc</p>
    </footer>
</div>

resources/views/backend/common/header.blade.php
<header class="p-3 bg-dark text-white">
    <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
                <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"/></svg>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li><a href="{{route('backend.home')}}" class="nav-link px-2 text-secondary">Home</a></li>
                <li><a href="{{route('backend.feedback.index')}}" class="nav-link px-2 text-white">Feedback</a></li>
            </ul>

        </div>
    </div>
</header>